name: AOSPA
on:
  workflow_dispatch:

jobs:
  
  build:
    name: AOSPA Official
    runs-on: ubuntu-latest    
    
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2    
    - name: Building AOSPA
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ env.HOST }}
        port: ${{ secrets.PORT }}
        private_key: ${{ env.SSH_PRIVATE_KEY }}
        script: ${{ secrets.AOSPA }}
