name: Evolution X
on: 
 workflow_dispatch
 
jobs:

  build:
    name: Evolution X Official
    runs-on: ubuntu-latest
    steps:
    - name: Evolution X building
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 400m
        script: ${{ secrets.EVOLUTION }}
